In [1]:
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", 50)


import dagshub
import mlflow

dagshub.init(
    repo_owner="sergi.gonzalez.martos",
    repo_name="MLOps_AlgoRhythm",
    mlflow=True
)

mlflow.set_experiment("spotify-song-popularity")
from src.config import MODELS_DIR, PROCESSED_DATA_DIR

# ----------------------------- CONFIGURATION -----------------------------

DATA_PATH = PROCESSED_DATA_DIR / "dataset_transformed.csv"
#DATA_PATH = "../data/processed/dataset_transformed.csv"
TARGET_COL = "popularity"
# --------------------------------------------------------------------------

c:\Users\amb20\OneDrive\Escritorio\MLOps\MLOps_AlgoRhythm\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Accessing as anamtzbarbosa

Initialized MLflow to track repo "sergi.gonzalez.martos/MLOps_AlgoRhythm"

Repository sergi.gonzalez.martos/MLOps_AlgoRhythm initialized!

2026-10-09 13:10:53.137 | INFO     | src.config:<module>:11 - PROJ_ROOT path is: C:\Users\amb20\OneDrive\Escritorio\MLOps\MLOps_AlgoRhythm

In [2]:

df = pd.read_csv(DATA_PATH)

df['explicit'] = df['explicit'].astype(int)


print(f"Loaded dataset: {df.shape[0]:,} rows x {df.shape[1]} columns")
display(df.head())

Loaded dataset: 108,646 rows x 129 columns

,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,genre_acoustic,genre_afrobeat,genre_alt-rock,genre_alternative,genre_ambient,genre_anime,genre_black-metal,genre_bluegrass,genre_blues,genre_brazil,...,genre_reggaeton,genre_rock,genre_rock-n-roll,genre_rockabilly,genre_romance,genre_sad,genre_salsa,genre_samba,genre_sertanejo,genre_show-tunes,genre_singer-songwriter,genre_ska,genre_sleep,genre_songwriter,genre_soul,genre_spanish,genre_study,genre_swedish,genre_synth-pop,genre_tango,genre_techno,genre_trance,genre_trip-hop,genre_turkish,genre_world-music
0,73,230666,0,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,55,149610,0,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,57,210826,0,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,71,201933,0,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,82,198853,0,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
col_numericas = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
col_booleanas = df.select_dtypes(include=['bool']).columns.tolist()
col_texto = df.select_dtypes(include=['object', 'category']).columns.tolist()

generos_one_hot = [col for col in df.columns if col.startswith('genre_')]
metricas_audio = [col for col in df.columns if col not in generos_one_hot and col != 'explicit']

print(f"numeric: {len(col_numericas)}")
print(f"bool: {len(col_booleanas)}")
print(f"text: {len(col_texto)}")
print(f"genre one hot encoded: {len(generos_one_hot)}")

resumen_columnas = pd.DataFrame({
    'type': df.dtypes,
    'nulls': df.isnull().sum(),
    'unique': df.nunique()
})

resumen_columnas.head(20)

numeric: 129
bool: 0
text: 0
genre one hot encoded: 114

                  Tipo_Dato  Valores_Nulos  Valores_Unicos
popularity            int64              0             101
duration_ms           int64              0           47671
explicit              int64              0               2
danceability        float64              0            1087
energy              float64              0            1559
key                   int64              0              12
loudness            float64              0           17233
mode                  int64              0               2
speechiness         float64              0            1081
acousticness        float64              0            5057
instrumentalness    float64              0            5344
liveness            float64              0            1722
valence             float64              0            1721
tempo               float64              0           42980
time_signature        int64              0               5
genre_acoustic        int64              0               2
genre_afrobeat        int64              0               2
genre_alt-rock        int64              0               2
genre_alternative     int64              0               2
genre_ambient         int64              0               2

## All audio features

In [15]:
audio_features = [
    'duration_ms', 'danceability', 'energy', 'key', 'loudness',
    'mode', 'speechiness', 'acousticness', 'instrumentalness',
    'liveness', 'valence', 'tempo', 'time_signature', 'explicit'
]
target = 'popularity'
X = df[audio_features]
y = df[target]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Linear Regression

In [16]:

# Scale data and Linear Regression
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

# Train and predict
with mlflow.start_run(run_name="linear-regression"):
    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    # Metrics
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    # Log parameters
    mlflow.log_param("model", "LinearRegression")
    mlflow.log_param("features", ", ".join(audio_features))
    mlflow.log_param("test_size", 0.2)
    mlflow.log_param("random_state", 42)

    # Log metrics
    mlflow.log_metric("mae", mae)
    mlflow.log_metric("rmse", rmse)
    mlflow.log_metric("r2", r2)
    print(f"MAE: {mae:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R2 Score: {r2:.2f}")

MAE: 18.48
RMSE: 22.12
R2 Score: 0.03
🏃 View run linear-regression at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/0/runs/9a455f351f6a4904b9cfb923163d856c
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/0

In [17]:
print("y_test:")
print(y_test.describe())

print("\ny_pred:")
print(pd.Series(y_pred).describe())

print("\nFirst 10 predictions:")
print(pd.DataFrame({
    "actual": y_test.iloc[:10].values,
    "predicted": y_pred[:10]
}))

y_test:
count    21730.000000
mean        33.295444
std         22.405097
min          0.000000
25%         17.000000
50%         35.000000
75%         50.000000
max         98.000000
Name: popularity, dtype: float64

y_pred:
count    21730.000000
mean        33.385905
std          3.788190
min         12.410595
25%         31.354318
50%         33.752703
75%         35.997922
max         46.422270
dtype: float64

First 10 predictions:
   actual  predicted
0      45  37.453266
1       3  32.847706
2      40  36.305810
3       0  23.077881
4      27  32.999303
5       5  32.533174
6      56  35.971713
7       0  35.403510
8      74  41.113775
9      28  34.402583

### Random Forest Regressor

In [ ]:
# Train and predict
N_ESTIMATORS = 100
with mlflow.start_run(run_name="rfr"):
    rf_model = RandomForestRegressor(
        n_estimators=N_ESTIMATORS,
        random_state=42,
        n_jobs=-1
    )

    rf_model.fit(X_train, y_train)

    y_pred_rf = rf_model.predict(X_test)

    mae_rf = mean_absolute_error(y_test, y_pred_rf)
    rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
    r2_rf = r2_score(y_test, y_pred_rf)

# Log parameters
    mlflow.log_param("model", "RandomForestRegressor")
    mlflow.log_param("features", ", ".join(audio_features))
    mlflow.log_param("test_size", 0.2)
    mlflow.log_param("random_state", 42)
    mlflow.log_param("n_estimators", N_ESTIMATORS)

    # Log metrics
    mlflow.log_metric("mae", mae_rf)
    mlflow.log_metric("rmse", rmse_rf)
    mlflow.log_metric("r2", r2_rf)
    print(f"MAE: {mae:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R2 Score: {r2:.2f}")

MAE: 18.48
RMSE: 22.12
R2 Score: 0.03
🏃 View run rfr at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/0/runs/2154e1afab024066bdb83b2edfb4fa50
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/0

In [19]:
print("Actual mean:", y_test.mean())
print("RF prediction mean:", y_pred_rf.mean())

print("\nFirst 10 predictions:")
print(pd.DataFrame({
    "actual": y_test.iloc[:10].values,
    "predicted": y_pred_rf[:10]
}))

Actual mean: 33.29544408651633
RF prediction mean: 33.30922698736606

First 10 predictions:
   actual  predicted
0      45  37.585000
1       3   1.179905
2      40  41.380000
3       0  11.810000
4      27  44.927500
5       5  33.356667
6      56  32.540000
7       0  12.370000
8      74  66.070000
9      28  36.835000

### Gradient Boosting Regressor

In [ ]:
# Gradient Boosting
# Train and predict
N_ESTIMATORS = 100
with mlflow.start_run(run_name="gradient-boosting"):
    gb_model = GradientBoostingRegressor(
        n_estimators=N_ESTIMATORS,
        learning_rate=0.1,
        max_depth=3,
        random_state=42
    )

    gb_model.fit(X_train, y_train)

    # Predict
    y_pred_gb = gb_model.predict(X_test)

    # Gradient Boosting metrics
    mae_gb = mean_absolute_error(y_test, y_pred_gb)
    rmse_gb = np.sqrt(mean_squared_error(y_test, y_pred_gb))
    r2_gb = r2_score(y_test, y_pred_gb)

    # Log parameters
    mlflow.log_param("model", "GradientBoostingRegressor")
    mlflow.log_param("features", ", ".join(audio_features))
    mlflow.log_param("test_size", 0.2)
    mlflow.log_param("random_state", 42)
    mlflow.log_param("n_estimators", N_ESTIMATORS)

    # Log metrics
    mlflow.log_metric("mae", mae_gb)
    mlflow.log_metric("rmse", rmse_gb)
    mlflow.log_metric("r2", r2_gb)

    print(f"MAE:  {mae_gb:.2f}")
    print(f"RMSE: {rmse_gb:.2f}")
    print(f"R²:   {r2_gb:.2f}")

MAE:  17.66
RMSE: 21.39
R²:   0.09
🏃 View run gradient-boosting at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/0/runs/1a43790b9fc44eb39c31ccbf1597a43f
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/0

### results

In [21]:
results = pd.DataFrame({
    'Model': [
        'Linear Regression',
        'Random Forest',
        'Gradient Boosting'
    ],
    'MAE': [
        mae,
        mae_rf,
        mae_gb
    ],
    'RMSE': [
        rmse,
        rmse_rf,
        rmse_gb
    ],
    'R2': [
        r2,
        r2_rf,
        r2_gb
    ]
})

results

               Model        MAE       RMSE        R2
0  Linear Regression  18.480155  22.116763  0.025528
1      Random Forest  10.650316  15.042763  0.549202
2  Gradient Boosting  17.656494  21.387601  0.088723

## Genre features as one hote

In [3]:
import pandas as pd
from scipy.stats import spearmanr
from src.config import PROCESSED_DATA_DIR, TRAIN_FILE

df = pd.read_csv(PROCESSED_DATA_DIR / TRAIN_FILE)
target = "popularity"

In [ ]:

# 1) instrumentalness
rho, p = spearmanr(df["instrumentalness"], df[target])
print(f"Spearman: {rho:.3f} (p={p:.3g})")
bins = pd.cut(df["instrumentalness"], [-0.01, 0.001, 0.1, 0.5, 1.0])
print(df.groupby(bins, observed=True)[target].agg(["mean", "count"]))

# 2 genre and popularity per genre
genre_cols = [c for c in df.columns if c.startswith("genre_")]
stats = pd.DataFrame({
    "mean_pop": {c: df.loc[df[c] == 1, target].mean() for c in genre_cols},
    "n": df[genre_cols].sum(),
}).sort_values("mean_pop")
print(stats.loc[["genre_grindcore", "genre_pop"]])
print(stats.head(10), stats.tail(10))

Spearman: -0.145 (p=0)
                       mean  count
instrumentalness
(-0.01, 0.001]    37.576772  50585
(0.001, 0.1]      35.741024  12673
(0.1, 0.5]        32.915776   5331
(0.5, 1.0]        28.588818  12914
                  mean_pop    n
genre_grindcore  14.731103  807
genre_pop        54.447178  691
                       mean_pop    n
genre_iranian          1.882263  654
genre_romance          3.600852  704
genre_latin           10.514658  614
genre_detroit-techno  11.160544  735
genre_chicago-house   12.410977  747
genre_grindcore       14.731103  807
genre_kids            15.112925  735
genre_idm             15.786382  749
genre_classical       16.308036  448
genre_honky-tonk      16.608527  774                           mean_pop    n
genre_progressive-house  48.038660  776
genre_anime              48.605744  766
genre_emo                49.174603  756
genre_indian             49.875654  764
genre_grunge             50.160354  792
genre_sad                52.701665  781
genre_pop                54.447178  691
genre_chill              54.458225  766
genre_k-pop              58.349081  762
genre_pop-film           59.013716  802

In [1]:
## Test production

from pathlib import Path

import dagshub
import mlflow
import numpy as np
import pandas as pd
import yaml
from codecarbon import EmissionsTracker
from loguru import logger
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from src.config import MODELS_DIR, PROCESSED_DATA_DIR, TEST_FILE, TRAIN_FILE

c:\Users\amb20\OneDrive\Escritorio\MLOps\MLOps_AlgoRhythm\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026-10-16 23:30:54.592 | INFO     | src.config:<module>:11 - PROJ_ROOT path is: C:\Users\amb20\OneDrive\Escritorio\MLOps\MLOps_AlgoRhythm

In [4]:
data_path = PROCESSED_DATA_DIR
MODEL_PATH = MODELS_DIR / "random_forest.pkl"
train_df = pd.read_csv(data_path / TRAIN_FILE)
test_df = pd.read_csv(data_path / TEST_FILE)
target = 'popularity'

X_train = train_df.drop(columns=[target])
y_train = train_df[target]
X_test = test_df.drop(columns=[target])
y_test = test_df[target]

X_train.columns

Index(['duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness',
       ...
       'genre_spanish', 'genre_study', 'genre_swedish', 'genre_synth-pop',
       'genre_tango', 'genre_techno', 'genre_trance', 'genre_trip-hop',
       'genre_turkish', 'genre_world-music'],
      dtype='str', length=128)

In [5]:
X_train.columns[:20]

Index(['duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'genre_acoustic',
       'genre_afrobeat', 'genre_alt-rock', 'genre_alternative',
       'genre_ambient', 'genre_anime'],
      dtype='str')

In [6]:
from pathlib import Path
print(Path.cwd())

c:\Users\amb20\OneDrive\Escritorio\MLOps\MLOps_AlgoRhythm\notebooks

## All numeric variables + genre one hot

In [ ]:
PROJ_ROOT = Path.cwd().parent  

with open(PROJ_ROOT / "params.yaml", encoding="utf-8") as f:
    params = yaml.safe_load(f)

target = params["global"]["target"]
seed = params["global"]["seed"]
test_split = params["split-data"]["test_split"]

dagshub.init(
    repo_owner="sergi.gonzalez.martos",
    repo_name="MLOps_AlgoRhythm",
    mlflow=True,
)
mlflow.set_experiment("spotify-song-popularity-testing")


def run_experiment(run_name, **hyperparams):
    tracker = EmissionsTracker(project_name="spotify_rf_experiment", save_to_file=False)

    with mlflow.start_run(run_name=run_name):
        mlflow.set_tag("model_stage", "experiment")

        model = RandomForestRegressor(random_state=seed, n_jobs=-1, **hyperparams)

        tracker.start()
        try:
            model.fit(X_train, y_train)
            predictions = model.predict(X_test)
        finally:
            tracker.stop()

        mae = mean_absolute_error(y_test, predictions)
        rmse = np.sqrt(mean_squared_error(y_test, predictions))
        r2 = r2_score(y_test, predictions)

        mlflow.log_param("model", "RandomForestRegressor")
        mlflow.log_param("random_state", seed)
        mlflow.log_param("test_size", test_split)
        mlflow.log_params(hyperparams)  
        mlflow.log_metrics({"mae": mae, "rmse": rmse, "r2": r2})
        mlflow.log_param("n_features", X_train.shape[1])
        mlflow.log_dict({"features": list(X_train.columns)}, "features.json")
        #importances = pd.Series(model.feature_importances_, index=X_train.columns).sort_values(ascending=False)
        #mlflow.log_dict(importances.to_dict(), "feature_importances.json")
        #mlflow.log_metrics({f"imp_top{i+1}_{name}": val for i, (name, val) in enumerate(importances.head(5).items())})

        data = tracker.final_emissions_data
        mlflow.log_metrics({
            "co2_emissions_kg": getattr(data, "emissions", 0.0) or 0.0,
            "energy_consumed_kwh": getattr(data, "energy_consumed", 0.0) or 0.0,
            "compute_duration_seconds": getattr(data, "duration", 0.0) or 0.0,
        })

        print(f"{run_name}: MAE={mae:.2f} RMSE={rmse:.2f} R2={r2:.3f}")



experiments = {
    "rf-baseline": {"n_estimators": 100},
    "rf-n200": {"n_estimators": 200},
    "rf-depth20": {"n_estimators": 200, "max_depth": 20},
    "rf-leaf5": {"n_estimators": 200, "min_samples_leaf": 5},
    "rf-maxfeat05": {"n_estimators": 200, "max_features": 0.5},
}

for name, hp in experiments.items():
    run_experiment(name, **hp)

Initialized MLflow to track repo "sergi.gonzalez.martos/MLOps_AlgoRhythm"

Repository sergi.gonzalez.martos/MLOps_AlgoRhythm initialized!

[codecarbon WARNING @ 23:34:32] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 23:34:36] >>> Tracker's metadata:
[codecarbon INFO @ 23:34:36]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 23:34:36]   Python version: 3.11.9
[codecarbon INFO @ 23:34:36]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 23:34:36]   Available RAM : 9.940 GB
[codecarbon INFO @ 23:34:36]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 23:34:36]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 23:34:36]   GPU count: 0
[codecarbon INFO @ 23:34:36]   GPU model:
[codecarbon INFO @ 23:34:36] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:34:36] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 9.579289787807435 W
[codecarbon INFO @ 23:34:36] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 23:34:36] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:34:51] Energy consumed for RAM : 0.000042 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:34:51] Delta energy consumed for CPU with windows_emi : 0.000053 kWh, power : 12.694932424613665 W
[codecarbon INFO @ 23:34:51] Energy consumed for All CPU : 0.000053 kWh
[codecarbon INFO @ 23:34:51] 0.000095 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:35:06] Energy consumed for RAM : 0.000084 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:35:06] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 12.78541484180801 W
[codecarbon INFO @ 23:35:06] Energy consumed for All CPU : 0.000107 kWh
[codecarbon INFO @ 23:35:06] 0.000190 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:35:21] Energy consumed for RAM : 0.000125 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:35:21] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.048795334432073 W
[codecarbon INFO @ 23:35:21] Energy consumed for All CPU : 0.000161 kWh
[codecarbon INFO @ 23:35:21] 0.000287 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:35:36] Energy consumed for RAM : 0.000167 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:35:36] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.262180531218723 W
[codecarbon INFO @ 23:35:36] Energy consumed for All CPU : 0.000217 kWh
[codecarbon INFO @ 23:35:36] 0.000384 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:35:51] Energy consumed for RAM : 0.000209 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:35:51] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.345288403962096 W
[codecarbon INFO @ 23:35:51] Energy consumed for All CPU : 0.000273 kWh
[codecarbon INFO @ 23:35:51] 0.000482 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:36:06] Energy consumed for RAM : 0.000251 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:36:06] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.304963710194889 W
[codecarbon INFO @ 23:36:06] Energy consumed for All CPU : 0.000329 kWh
[codecarbon INFO @ 23:36:06] 0.000579 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:36:21] Energy consumed for RAM : 0.000293 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:36:21] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.157990644704112 W
[codecarbon INFO @ 23:36:21] Energy consumed for All CPU : 0.000383 kWh
[codecarbon INFO @ 23:36:21] 0.000676 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:36:36] Energy consumed for RAM : 0.000334 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:36:36] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.233418589884081 W
[codecarbon INFO @ 23:36:36] Energy consumed for All CPU : 0.000439 kWh
[codecarbon INFO @ 23:36:36] 0.000773 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:36:52] Energy consumed for RAM : 0.000376 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:36:52] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.055640344150376 W
[codecarbon INFO @ 23:36:52] Energy consumed for All CPU : 0.000494 kWh
[codecarbon INFO @ 23:36:52] 0.000870 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:37:07] Energy consumed for RAM : 0.000418 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:37:07] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.341542167382139 W
[codecarbon INFO @ 23:37:07] Energy consumed for All CPU : 0.000550 kWh
[codecarbon INFO @ 23:37:07] 0.000968 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:37:22] Energy consumed for RAM : 0.000460 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:37:22] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.387659492715558 W
[codecarbon INFO @ 23:37:22] Energy consumed for All CPU : 0.000606 kWh
[codecarbon INFO @ 23:37:22] 0.001066 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:37:37] Energy consumed for RAM : 0.000502 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:37:37] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.265434871306072 W
[codecarbon INFO @ 23:37:37] Energy consumed for All CPU : 0.000661 kWh
[codecarbon INFO @ 23:37:37] 0.001163 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:37:43] Energy consumed for RAM : 0.000519 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:37:43] Delta energy consumed for CPU with windows_emi : 0.000022 kWh, power : 12.965148010346823 W
[codecarbon INFO @ 23:37:43] Energy consumed for All CPU : 0.000683 kWh
[codecarbon INFO @ 23:37:43] 0.001202 kWh of electricity and 0.000000 L of water were used since the beginning.

rf-baseline: MAE=11.03 RMSE=15.89 R2=0.441
🏃 View run rf-baseline at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/4e14e5915f3041b4bab31f87732258e1
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

[codecarbon WARNING @ 23:37:51] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 23:37:58] >>> Tracker's metadata:
[codecarbon INFO @ 23:37:58]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 23:37:58]   Python version: 3.11.9
[codecarbon INFO @ 23:37:58]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 23:37:58]   Available RAM : 9.940 GB
[codecarbon INFO @ 23:37:58]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 23:37:58]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 23:37:58]   GPU count: 0
[codecarbon INFO @ 23:37:58]   GPU model:
[codecarbon INFO @ 23:37:58] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:37:58] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 7.053825623217165 W
[codecarbon INFO @ 23:37:58] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 23:37:58] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:38:13] Energy consumed for RAM : 0.000042 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:38:13] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 12.951866568367507 W
[codecarbon INFO @ 23:38:13] Energy consumed for All CPU : 0.000054 kWh
[codecarbon INFO @ 23:38:13] 0.000096 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:38:28] Energy consumed for RAM : 0.000084 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:38:28] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.195039146320914 W
[codecarbon INFO @ 23:38:28] Energy consumed for All CPU : 0.000110 kWh
[codecarbon INFO @ 23:38:28] 0.000193 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:38:43] Energy consumed for RAM : 0.000125 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:38:43] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.11471573532693 W
[codecarbon INFO @ 23:38:43] Energy consumed for All CPU : 0.000164 kWh
[codecarbon INFO @ 23:38:43] 0.000290 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:38:58] Energy consumed for RAM : 0.000167 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:38:58] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.088883122426038 W
[codecarbon INFO @ 23:38:58] Energy consumed for All CPU : 0.000219 kWh
[codecarbon INFO @ 23:38:58] 0.000386 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:39:13] Energy consumed for RAM : 0.000209 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:39:13] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.142913768026766 W
[codecarbon INFO @ 23:39:13] Energy consumed for All CPU : 0.000274 kWh
[codecarbon INFO @ 23:39:13] 0.000482 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:39:28] Energy consumed for RAM : 0.000250 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:39:28] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 13.047006580948056 W
[codecarbon INFO @ 23:39:28] Energy consumed for All CPU : 0.000328 kWh
[codecarbon INFO @ 23:39:28] 0.000579 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:39:43] Energy consumed for RAM : 0.000292 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:39:43] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.150672026877096 W
[codecarbon INFO @ 23:39:43] Energy consumed for All CPU : 0.000383 kWh
[codecarbon INFO @ 23:39:43] 0.000675 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:39:58] Energy consumed for RAM : 0.000334 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:39:58] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.155202380326697 W
[codecarbon INFO @ 23:39:58] Energy consumed for All CPU : 0.000438 kWh
[codecarbon INFO @ 23:39:58] 0.000772 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:40:13] Energy consumed for RAM : 0.000376 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:40:13] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.214040730272432 W
[codecarbon INFO @ 23:40:13] Energy consumed for All CPU : 0.000494 kWh
[codecarbon INFO @ 23:40:13] 0.000869 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:40:28] Energy consumed for RAM : 0.000418 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:40:28] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.194686991989078 W
[codecarbon INFO @ 23:40:28] Energy consumed for All CPU : 0.000549 kWh
[codecarbon INFO @ 23:40:28] 0.000967 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:40:43] Energy consumed for RAM : 0.000460 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:40:43] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.115235133509856 W
[codecarbon INFO @ 23:40:43] Energy consumed for All CPU : 0.000604 kWh
[codecarbon INFO @ 23:40:43] 0.001064 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:40:58] Energy consumed for RAM : 0.000501 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:40:58] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 13.046198547170405 W
[codecarbon INFO @ 23:40:58] Energy consumed for All CPU : 0.000659 kWh
[codecarbon INFO @ 23:40:58] 0.001160 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:41:13] Energy consumed for RAM : 0.000543 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:41:13] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.066081076272111 W
[codecarbon INFO @ 23:41:13] Energy consumed for All CPU : 0.000713 kWh
[codecarbon INFO @ 23:41:13] 0.001256 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:41:28] Energy consumed for RAM : 0.000585 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:41:28] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.053426091368939 W
[codecarbon INFO @ 23:41:28] Energy consumed for All CPU : 0.000768 kWh
[codecarbon INFO @ 23:41:28] 0.001353 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:41:43] Energy consumed for RAM : 0.000627 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:41:43] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 13.026815938948676 W
[codecarbon INFO @ 23:41:43] Energy consumed for All CPU : 0.000822 kWh
[codecarbon INFO @ 23:41:43] 0.001449 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:41:59] Energy consumed for RAM : 0.000668 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:41:59] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.04066436335464 W
[codecarbon INFO @ 23:41:59] Energy consumed for All CPU : 0.000877 kWh
[codecarbon INFO @ 23:41:59] 0.001545 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:42:14] Energy consumed for RAM : 0.000710 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:42:14] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 13.02158584050963 W
[codecarbon INFO @ 23:42:14] Energy consumed for All CPU : 0.000931 kWh
[codecarbon INFO @ 23:42:14] 0.001641 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:42:29] Energy consumed for RAM : 0.000752 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:42:29] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.058605073864527 W
[codecarbon INFO @ 23:42:29] Energy consumed for All CPU : 0.000986 kWh
[codecarbon INFO @ 23:42:29] 0.001738 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:42:44] Energy consumed for RAM : 0.000794 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:42:44] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.153322081283282 W
[codecarbon INFO @ 23:42:44] Energy consumed for All CPU : 0.001041 kWh
[codecarbon INFO @ 23:42:44] 0.001834 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:42:59] Energy consumed for RAM : 0.000835 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:42:59] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.221485232963888 W
[codecarbon INFO @ 23:42:59] Energy consumed for All CPU : 0.001096 kWh
[codecarbon INFO @ 23:42:59] 0.001931 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:43:14] Energy consumed for RAM : 0.000877 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:43:14] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.203489782259304 W
[codecarbon INFO @ 23:43:14] Energy consumed for All CPU : 0.001151 kWh
[codecarbon INFO @ 23:43:14] 0.002028 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:43:29] Energy consumed for RAM : 0.000919 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:43:29] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.125956079133397 W
[codecarbon INFO @ 23:43:29] Energy consumed for All CPU : 0.001206 kWh
[codecarbon INFO @ 23:43:29] 0.002125 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:43:37] Energy consumed for RAM : 0.000943 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:43:37] Delta energy consumed for CPU with windows_emi : 0.000031 kWh, power : 12.913074515760258 W
[codecarbon INFO @ 23:43:37] Energy consumed for All CPU : 0.001237 kWh
[codecarbon INFO @ 23:43:37] 0.002179 kWh of electricity and 0.000000 L of water were used since the beginning.

rf-n200: MAE=10.99 RMSE=15.83 R2=0.445
🏃 View run rf-n200 at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/83656bac980646d49d9065f32f06dd99
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

[codecarbon WARNING @ 23:43:47] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 23:43:55] >>> Tracker's metadata:
[codecarbon INFO @ 23:43:55]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 23:43:55]   Python version: 3.11.9
[codecarbon INFO @ 23:43:55]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 23:43:55]   Available RAM : 9.940 GB
[codecarbon INFO @ 23:43:55]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 23:43:55]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 23:43:55]   GPU count: 0
[codecarbon INFO @ 23:43:55]   GPU model:
[codecarbon INFO @ 23:43:55] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:43:55] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 7.585655099848747 W
[codecarbon INFO @ 23:43:55] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 23:43:55] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:44:10] Energy consumed for RAM : 0.000042 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:44:10] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.205059804322055 W
[codecarbon INFO @ 23:44:10] Energy consumed for All CPU : 0.000055 kWh
[codecarbon INFO @ 23:44:10] 0.000097 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:44:25] Energy consumed for RAM : 0.000084 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:44:25] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.257736828825285 W
[codecarbon INFO @ 23:44:25] Energy consumed for All CPU : 0.000111 kWh
[codecarbon INFO @ 23:44:25] 0.000194 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:44:40] Energy consumed for RAM : 0.000125 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:44:40] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.313254153628726 W
[codecarbon INFO @ 23:44:40] Energy consumed for All CPU : 0.000166 kWh
[codecarbon INFO @ 23:44:40] 0.000292 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:44:55] Energy consumed for RAM : 0.000167 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:44:55] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.184599999957552 W
[codecarbon INFO @ 23:44:55] Energy consumed for All CPU : 0.000222 kWh
[codecarbon INFO @ 23:44:55] 0.000389 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:45:11] Energy consumed for RAM : 0.000210 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:45:11] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.247179384402662 W
[codecarbon INFO @ 23:45:11] Energy consumed for All CPU : 0.000278 kWh
[codecarbon INFO @ 23:45:11] 0.000487 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:45:26] Energy consumed for RAM : 0.000251 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:45:26] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.299275126555573 W
[codecarbon INFO @ 23:45:26] Energy consumed for All CPU : 0.000333 kWh
[codecarbon INFO @ 23:45:26] 0.000585 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:45:41] Energy consumed for RAM : 0.000293 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:45:41] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.446474398439737 W
[codecarbon INFO @ 23:45:41] Energy consumed for All CPU : 0.000390 kWh
[codecarbon INFO @ 23:45:41] 0.000683 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:45:56] Energy consumed for RAM : 0.000335 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:45:56] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.18654305450007 W
[codecarbon INFO @ 23:45:56] Energy consumed for All CPU : 0.000445 kWh
[codecarbon INFO @ 23:45:56] 0.000780 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:46:11] Energy consumed for RAM : 0.000377 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:46:11] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.371328709831392 W
[codecarbon INFO @ 23:46:11] Energy consumed for All CPU : 0.000501 kWh
[codecarbon INFO @ 23:46:11] 0.000877 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:46:26] Energy consumed for RAM : 0.000418 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:46:26] Delta energy consumed for CPU with windows_emi : 0.000056 kWh, power : 13.3383652431048 W
[codecarbon INFO @ 23:46:26] Energy consumed for All CPU : 0.000556 kWh
[codecarbon INFO @ 23:46:26] 0.000975 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:46:29] Energy consumed for RAM : 0.000427 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:46:29] Delta energy consumed for CPU with windows_emi : 0.000011 kWh, power : 13.039183329546004 W
[codecarbon INFO @ 23:46:29] Energy consumed for All CPU : 0.000568 kWh
[codecarbon INFO @ 23:46:29] 0.000994 kWh of electricity and 0.000000 L of water were used since the beginning.

rf-depth20: MAE=14.21 RMSE=18.63 R2=0.232
🏃 View run rf-depth20 at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/eaee9b8b12ee4c198d26031b436d5a7b
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

[codecarbon WARNING @ 23:46:34] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 23:46:46] >>> Tracker's metadata:
[codecarbon INFO @ 23:46:46]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 23:46:46]   Python version: 3.11.9
[codecarbon INFO @ 23:46:46]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 23:46:46]   Available RAM : 9.940 GB
[codecarbon INFO @ 23:46:46]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 23:46:46]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 23:46:46]   GPU count: 0
[codecarbon INFO @ 23:46:46]   GPU model:
[codecarbon INFO @ 23:46:46] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:46:46] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 10.189359316046069 W
[codecarbon INFO @ 23:46:46] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 23:46:46] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:47:01] Energy consumed for RAM : 0.000042 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:47:01] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 12.915876851902649 W
[codecarbon INFO @ 23:47:01] Energy consumed for All CPU : 0.000054 kWh
[codecarbon INFO @ 23:47:01] 0.000096 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:47:16] Energy consumed for RAM : 0.000083 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:47:16] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 13.01368785249931 W
[codecarbon INFO @ 23:47:16] Energy consumed for All CPU : 0.000108 kWh
[codecarbon INFO @ 23:47:16] 0.000192 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:47:31] Energy consumed for RAM : 0.000125 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:47:31] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.080469324873212 W
[codecarbon INFO @ 23:47:31] Energy consumed for All CPU : 0.000163 kWh
[codecarbon INFO @ 23:47:31] 0.000288 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:47:46] Energy consumed for RAM : 0.000167 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:47:46] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.175040125075958 W
[codecarbon INFO @ 23:47:46] Energy consumed for All CPU : 0.000218 kWh
[codecarbon INFO @ 23:47:46] 0.000385 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:48:01] Energy consumed for RAM : 0.000209 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:48:01] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.12971849948779 W
[codecarbon INFO @ 23:48:01] Energy consumed for All CPU : 0.000273 kWh
[codecarbon INFO @ 23:48:01] 0.000482 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:48:16] Energy consumed for RAM : 0.000250 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:48:16] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.126900570580924 W
[codecarbon INFO @ 23:48:16] Energy consumed for All CPU : 0.000328 kWh
[codecarbon INFO @ 23:48:16] 0.000578 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:48:31] Energy consumed for RAM : 0.000292 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:48:31] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.160350364897374 W
[codecarbon INFO @ 23:48:31] Energy consumed for All CPU : 0.000383 kWh
[codecarbon INFO @ 23:48:31] 0.000675 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:48:46] Energy consumed for RAM : 0.000334 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:48:46] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.094324309057976 W
[codecarbon INFO @ 23:48:46] Energy consumed for All CPU : 0.000438 kWh
[codecarbon INFO @ 23:48:46] 0.000772 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:49:01] Energy consumed for RAM : 0.000376 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:49:01] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.135515981005977 W
[codecarbon INFO @ 23:49:01] Energy consumed for All CPU : 0.000492 kWh
[codecarbon INFO @ 23:49:01] 0.000868 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:49:16] Energy consumed for RAM : 0.000417 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:49:16] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.148085339118856 W
[codecarbon INFO @ 23:49:16] Energy consumed for All CPU : 0.000547 kWh
[codecarbon INFO @ 23:49:16] 0.000965 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:49:31] Energy consumed for RAM : 0.000459 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:49:31] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.15021802330038 W
[codecarbon INFO @ 23:49:31] Energy consumed for All CPU : 0.000602 kWh
[codecarbon INFO @ 23:49:31] 0.001061 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:49:46] Energy consumed for RAM : 0.000501 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:49:46] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.139015126128077 W
[codecarbon INFO @ 23:49:46] Energy consumed for All CPU : 0.000657 kWh
[codecarbon INFO @ 23:49:46] 0.001158 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:50:01] Energy consumed for RAM : 0.000543 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:50:01] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.182518607545735 W
[codecarbon INFO @ 23:50:01] Energy consumed for All CPU : 0.000712 kWh
[codecarbon INFO @ 23:50:01] 0.001255 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:50:16] Energy consumed for RAM : 0.000584 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:50:16] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.171389736882224 W
[codecarbon INFO @ 23:50:16] Energy consumed for All CPU : 0.000767 kWh
[codecarbon INFO @ 23:50:16] 0.001352 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:50:32] Energy consumed for RAM : 0.000626 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:50:32] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.209879348246806 W
[codecarbon INFO @ 23:50:32] Energy consumed for All CPU : 0.000822 kWh
[codecarbon INFO @ 23:50:32] 0.001449 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:50:47] Energy consumed for RAM : 0.000668 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:50:47] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.197098411027907 W
[codecarbon INFO @ 23:50:47] Energy consumed for All CPU : 0.000878 kWh
[codecarbon INFO @ 23:50:47] 0.001545 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:51:02] Energy consumed for RAM : 0.000710 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:51:02] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.21791622785332 W
[codecarbon INFO @ 23:51:02] Energy consumed for All CPU : 0.000933 kWh
[codecarbon INFO @ 23:51:02] 0.001642 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:51:17] Energy consumed for RAM : 0.000751 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:51:17] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.22288939824453 W
[codecarbon INFO @ 23:51:17] Energy consumed for All CPU : 0.000988 kWh
[codecarbon INFO @ 23:51:17] 0.001739 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:51:32] Energy consumed for RAM : 0.000793 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:51:32] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 13.030244065414546 W
[codecarbon INFO @ 23:51:32] Energy consumed for All CPU : 0.001042 kWh
[codecarbon INFO @ 23:51:32] 0.001835 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:51:47] Energy consumed for RAM : 0.000835 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:51:47] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 12.872227289674825 W
[codecarbon INFO @ 23:51:47] Energy consumed for All CPU : 0.001096 kWh
[codecarbon INFO @ 23:51:47] 0.001931 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:51:56] Energy consumed for RAM : 0.000861 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:51:56] Delta energy consumed for CPU with windows_emi : 0.000032 kWh, power : 12.232900943472636 W
[codecarbon INFO @ 23:51:56] Energy consumed for All CPU : 0.001129 kWh
[codecarbon INFO @ 23:51:56] 0.001990 kWh of electricity and 0.000000 L of water were used since the beginning.

rf-leaf5: MAE=11.37 RMSE=15.92 R2=0.439
🏃 View run rf-leaf5 at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/97dc5e1bb800463bb6a91961f0fb177d
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

[codecarbon WARNING @ 23:52:01] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 23:52:06] >>> Tracker's metadata:
[codecarbon INFO @ 23:52:06]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 23:52:06]   Python version: 3.11.9
[codecarbon INFO @ 23:52:06]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 23:52:06]   Available RAM : 9.940 GB
[codecarbon INFO @ 23:52:06]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 23:52:06]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 23:52:06]   GPU count: 0
[codecarbon INFO @ 23:52:06]   GPU model:
[codecarbon INFO @ 23:52:06] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:52:06] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 7.203362611585328 W
[codecarbon INFO @ 23:52:06] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 23:52:06] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:52:21] Energy consumed for RAM : 0.000042 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:52:21] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 12.926094394696534 W
[codecarbon INFO @ 23:52:21] Energy consumed for All CPU : 0.000054 kWh
[codecarbon INFO @ 23:52:21] 0.000096 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:52:36] Energy consumed for RAM : 0.000083 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:52:36] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.067544565198554 W
[codecarbon INFO @ 23:52:36] Energy consumed for All CPU : 0.000109 kWh
[codecarbon INFO @ 23:52:36] 0.000192 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:52:51] Energy consumed for RAM : 0.000125 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:52:51] Delta energy consumed for CPU with windows_emi : 0.000054 kWh, power : 13.030194733513524 W
[codecarbon INFO @ 23:52:51] Energy consumed for All CPU : 0.000163 kWh
[codecarbon INFO @ 23:52:51] 0.000288 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:53:06] Energy consumed for RAM : 0.000167 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:53:06] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.16576156888157 W
[codecarbon INFO @ 23:53:06] Energy consumed for All CPU : 0.000218 kWh
[codecarbon INFO @ 23:53:06] 0.000385 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:53:21] Energy consumed for RAM : 0.000209 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:53:21] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.146925178474557 W
[codecarbon INFO @ 23:53:21] Energy consumed for All CPU : 0.000273 kWh
[codecarbon INFO @ 23:53:21] 0.000482 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:53:36] Energy consumed for RAM : 0.000250 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:53:36] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.13542222077781 W
[codecarbon INFO @ 23:53:36] Energy consumed for All CPU : 0.000328 kWh
[codecarbon INFO @ 23:53:36] 0.000578 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:53:51] Energy consumed for RAM : 0.000292 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:53:51] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.086299170974145 W
[codecarbon INFO @ 23:53:51] Energy consumed for All CPU : 0.000382 kWh
[codecarbon INFO @ 23:53:51] 0.000675 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:54:06] Energy consumed for RAM : 0.000334 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:54:06] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.044318977344512 W
[codecarbon INFO @ 23:54:06] Energy consumed for All CPU : 0.000437 kWh
[codecarbon INFO @ 23:54:06] 0.000771 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:54:21] Energy consumed for RAM : 0.000376 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:54:21] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.061180362829363 W
[codecarbon INFO @ 23:54:21] Energy consumed for All CPU : 0.000492 kWh
[codecarbon INFO @ 23:54:21] 0.000867 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:54:36] Energy consumed for RAM : 0.000417 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:54:36] Delta energy consumed for CPU with windows_emi : 0.000055 kWh, power : 13.0805125615237 W
[codecarbon INFO @ 23:54:36] Energy consumed for All CPU : 0.000546 kWh
[codecarbon INFO @ 23:54:36] 0.000964 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 23:54:49] Energy consumed for RAM : 0.000453 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 23:54:49] Delta energy consumed for CPU with windows_emi : 0.000044 kWh, power : 12.251326722291994 W
[codecarbon INFO @ 23:54:49] Energy consumed for All CPU : 0.000590 kWh
[codecarbon INFO @ 23:54:49] 0.001044 kWh of electricity and 0.000000 L of water were used since the beginning.

rf-maxfeat05: MAE=11.00 RMSE=15.80 R2=0.448
🏃 View run rf-maxfeat05 at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/77adbe84b11046f99966c54ca1b4c7f3
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

In [8]:
from sklearn.ensemble import HistGradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor


def run_experiment(run_name, model_class, **hyperparams):
    tracker = EmissionsTracker(project_name="spotify_experiment", save_to_file=False)

    with mlflow.start_run(run_name=run_name):
        mlflow.set_tag("model_stage", "experiment")

        model = model_class(random_state=seed, **hyperparams)

        tracker.start()
        try:
            model.fit(X_train, y_train)
            predictions = model.predict(X_test)
        finally:
            tracker.stop()

        mae = mean_absolute_error(y_test, predictions)
        rmse = np.sqrt(mean_squared_error(y_test, predictions))
        r2 = r2_score(y_test, predictions)

        mlflow.log_param("model", model_class.__name__)
        mlflow.log_param("random_state", seed)
        mlflow.log_param("test_size", test_split)
        mlflow.log_params(hyperparams)
        mlflow.log_metrics({"mae": mae, "rmse": rmse, "r2": r2})
        mlflow.log_param("n_features", X_train.shape[1])
        mlflow.log_dict({"features": list(X_train.columns)}, "features.json")

        # HistGradientBoosting no tiene feature_importances_
        if hasattr(model, "feature_importances_"):
            importances = pd.Series(model.feature_importances_, index=X_train.columns)
            mlflow.log_dict(importances.sort_values(ascending=False).to_dict(),
                            "feature_importances.json")

        data = tracker.final_emissions_data
        mlflow.log_metrics({
            "co2_emissions_kg": getattr(data, "emissions", 0.0) or 0.0,
            "energy_consumed_kwh": getattr(data, "energy_consumed", 0.0) or 0.0,
            "compute_duration_seconds": getattr(data, "duration", 0.0) or 0.0,
        })
        print(f"{run_name}: MAE={mae:.3f} RMSE={rmse:.3f} R2={r2:.4f}")


experiments = {
    "hgb-base": (HistGradientBoostingRegressor,
                 {"max_iter": 500, "learning_rate": 0.05, "max_leaf_nodes": 63}),
    "lgbm-base": (LGBMRegressor,
                  {"n_estimators": 500, "learning_rate": 0.05, "num_leaves": 63,
                   "colsample_bytree": 0.5, "n_jobs": -1, "verbose": -1}),
    "xgb-base": (XGBRegressor,
                 {"n_estimators": 500, "learning_rate": 0.05, "max_depth": 8,
                  "subsample": 0.8, "colsample_bytree": 0.5, "n_jobs": -1}),
}

for name, (cls, hp) in experiments.items():
    run_experiment(name, cls, **hp)

[codecarbon WARNING @ 00:24:47] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 00:24:59] >>> Tracker's metadata:
[codecarbon INFO @ 00:24:59]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 00:24:59]   Python version: 3.11.9
[codecarbon INFO @ 00:24:59]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 00:24:59]   Available RAM : 9.940 GB
[codecarbon INFO @ 00:24:59]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 00:24:59]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 00:24:59]   GPU count: 0
[codecarbon INFO @ 00:24:59]   GPU model:
[codecarbon INFO @ 00:24:59] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 00:24:59] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 9.469353713768117 W
[codecarbon INFO @ 00:24:59] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 00:24:59] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 00:25:14] Energy consumed for RAM : 0.000042 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 00:25:14] Delta energy consumed for CPU with windows_emi : 0.000042 kWh, power : 9.969971401815227 W
[codecarbon INFO @ 00:25:14] Energy consumed for All CPU : 0.000042 kWh
[codecarbon INFO @ 00:25:14] 0.000083 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 00:25:29] Energy consumed for RAM : 0.000083 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 00:25:29] Delta energy consumed for CPU with windows_emi : 0.000039 kWh, power : 9.350926138378213 W
[codecarbon INFO @ 00:25:29] Energy consumed for All CPU : 0.000081 kWh
[codecarbon INFO @ 00:25:29] 0.000164 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 00:25:34] Energy consumed for RAM : 0.000097 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 00:25:34] Delta energy consumed for CPU with windows_emi : 0.000014 kWh, power : 9.67161043003136 W
[codecarbon INFO @ 00:25:34] Energy consumed for All CPU : 0.000094 kWh
[codecarbon INFO @ 00:25:34] 0.000192 kWh of electricity and 0.000000 L of water were used since the beginning.

hgb-base: MAE=12.116 RMSE=16.879 R2=0.3695
🏃 View run hgb-base at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/7f1cdbe41fa2445d903e8e93c1f4605c
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

[codecarbon WARNING @ 00:25:38] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 00:25:41] >>> Tracker's metadata:
[codecarbon INFO @ 00:25:41]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 00:25:41]   Python version: 3.11.9
[codecarbon INFO @ 00:25:41]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 00:25:41]   Available RAM : 9.940 GB
[codecarbon INFO @ 00:25:41]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 00:25:41]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 00:25:41]   GPU count: 0
[codecarbon INFO @ 00:25:41]   GPU model:
[codecarbon INFO @ 00:25:41] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 00:25:41] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 9.291591410796709 W
[codecarbon INFO @ 00:25:41] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 00:25:41] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 00:25:46] Energy consumed for RAM : 0.000012 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 00:25:46] Delta energy consumed for CPU with windows_emi : 0.000012 kWh, power : 9.675621516726418 W
[codecarbon INFO @ 00:25:46] Energy consumed for All CPU : 0.000012 kWh
[codecarbon INFO @ 00:25:46] 0.000024 kWh of electricity and 0.000000 L of water were used since the beginning.

lgbm-base: MAE=12.092 RMSE=16.845 R2=0.3721
🏃 View run lgbm-base at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/8f237288a72241d7bc797ff1d98276a7
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

[codecarbon WARNING @ 00:25:49] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 00:25:57] >>> Tracker's metadata:
[codecarbon INFO @ 00:25:57]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 00:25:57]   Python version: 3.11.9
[codecarbon INFO @ 00:25:57]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 00:25:57]   Available RAM : 9.940 GB
[codecarbon INFO @ 00:25:57]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 00:25:57]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 00:25:57]   GPU count: 0
[codecarbon INFO @ 00:25:57]   GPU model:
[codecarbon INFO @ 00:25:57] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 00:25:57] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 6.7409724378605524 W
[codecarbon INFO @ 00:25:57] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 00:25:57] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 00:26:09] Energy consumed for RAM : 0.000033 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 00:26:09] Delta energy consumed for CPU with windows_emi : 0.000034 kWh, power : 10.216203328568945 W
[codecarbon INFO @ 00:26:09] Energy consumed for All CPU : 0.000034 kWh
[codecarbon INFO @ 00:26:09] 0.000068 kWh of electricity and 0.000000 L of water were used since the beginning.

xgb-base: MAE=12.371 RMSE=17.297 R2=0.3380
🏃 View run xgb-base at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/59490ea22ef64a1c9e16fa18303190ec
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

#### Final test with no onehot

In [11]:
audio_features = [
    'duration_ms', 'danceability', 'energy', 'key', 'loudness',
    'mode', 'speechiness', 'acousticness', 'instrumentalness',
    'liveness', 'valence', 'tempo', 'time_signature', 'explicit'
]

data_path = PROCESSED_DATA_DIR
MODEL_PATH = MODELS_DIR / "random_forest.pkl"
train_df = pd.read_csv(data_path / TRAIN_FILE)
test_df = pd.read_csv(data_path / TEST_FILE)
target = 'popularity'

X_train = train_df[audio_features]
y_train = train_df[target]
X_test = test_df[audio_features]
y_test = test_df[target]

#X = df[audio_features]
#y = df[target]

PROJ_ROOT = Path.cwd().parent  

with open(PROJ_ROOT / "params.yaml", encoding="utf-8") as f:
    params = yaml.safe_load(f)

target = params["global"]["target"]
seed = params["global"]["seed"]
test_split = params["split-data"]["test_split"]

dagshub.init(
    repo_owner="sergi.gonzalez.martos",
    repo_name="MLOps_AlgoRhythm",
    mlflow=True,
)
mlflow.set_experiment("spotify-song-popularity-testing")


def run_experiment(run_name, **hyperparams):
    """Entrena un RF con los hiperparámetros dados y lo registra en MLflow."""
    tracker = EmissionsTracker(project_name="spotify_rf_experiment", save_to_file=False)

    with mlflow.start_run(run_name=run_name):
        mlflow.set_tag("model_stage", "experiment")

        model = RandomForestRegressor(random_state=seed, n_jobs=-1, **hyperparams)

        tracker.start()
        try:
            model.fit(X_train, y_train)
            predictions = model.predict(X_test)
        finally:
            tracker.stop()

        mae = mean_absolute_error(y_test, predictions)
        rmse = np.sqrt(mean_squared_error(y_test, predictions))
        r2 = r2_score(y_test, predictions)

        mlflow.log_param("model", "RandomForestRegressor")
        mlflow.log_param("random_state", seed)
        mlflow.log_param("test_size", test_split)
        mlflow.log_params(hyperparams)  
        mlflow.log_metrics({"mae": mae, "rmse": rmse, "r2": r2})
        mlflow.log_param("n_features", X_train.shape[1])
        mlflow.log_dict({"features": list(X_train.columns)}, "features.json")
        #importances = pd.Series(model.feature_importances_, index=X_train.columns).sort_values(ascending=False)
        #mlflow.log_dict(importances.to_dict(), "feature_importances.json")
        #mlflow.log_metrics({f"imp_top{i+1}_{name}": val for i, (name, val) in enumerate(importances.head(5).items())})

        data = tracker.final_emissions_data
        mlflow.log_metrics({
            "co2_emissions_kg": getattr(data, "emissions", 0.0) or 0.0,
            "energy_consumed_kwh": getattr(data, "energy_consumed", 0.0) or 0.0,
            "compute_duration_seconds": getattr(data, "duration", 0.0) or 0.0,
        })

        print(f"{run_name}: MAE={mae:.2f} RMSE={rmse:.2f} R2={r2:.3f}")



experiments = {
    "rf-baseline": {"n_estimators": 100},
    "rf-n200": {"n_estimators": 200},
    "rf-maxfeat05": {"n_estimators": 200, "max_features": 0.5},
}

for name, hp in experiments.items():
    run_experiment(name, **hp)

Initialized MLflow to track repo "sergi.gonzalez.martos/MLOps_AlgoRhythm"

Repository sergi.gonzalez.martos/MLOps_AlgoRhythm initialized!

[codecarbon WARNING @ 11:36:45] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 11:36:52] >>> Tracker's metadata:
[codecarbon INFO @ 11:36:52]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 11:36:52]   Python version: 3.11.9
[codecarbon INFO @ 11:36:52]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 11:36:52]   Available RAM : 9.940 GB
[codecarbon INFO @ 11:36:52]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 11:36:52]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 11:36:52]   GPU count: 0
[codecarbon INFO @ 11:36:52]   GPU model:
[codecarbon INFO @ 11:36:52] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:36:52] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 7.367275780310406 W
[codecarbon INFO @ 11:36:52] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 11:36:52] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:37:07] Energy consumed for RAM : 0.000042 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:37:07] Delta energy consumed for CPU with windows_emi : 0.000040 kWh, power : 9.463833178026151 W
[codecarbon INFO @ 11:37:07] Energy consumed for All CPU : 0.000040 kWh
[codecarbon INFO @ 11:37:07] 0.000082 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:37:22] Energy consumed for RAM : 0.000084 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:37:22] Delta energy consumed for CPU with windows_emi : 0.000045 kWh, power : 10.767295067304063 W
[codecarbon INFO @ 11:37:22] Energy consumed for All CPU : 0.000085 kWh
[codecarbon INFO @ 11:37:22] 0.000169 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:37:37] Energy consumed for RAM : 0.000126 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:37:37] Delta energy consumed for CPU with windows_emi : 0.000040 kWh, power : 9.618360126385658 W
[codecarbon INFO @ 11:37:37] Energy consumed for All CPU : 0.000126 kWh
[codecarbon INFO @ 11:37:37] 0.000252 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:37:44] Energy consumed for RAM : 0.000146 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:37:44] Delta energy consumed for CPU with windows_emi : 0.000019 kWh, power : 9.355296174292771 W
[codecarbon INFO @ 11:37:44] Energy consumed for All CPU : 0.000144 kWh
[codecarbon INFO @ 11:37:44] 0.000290 kWh of electricity and 0.000000 L of water were used since the beginning.

rf-baseline: MAE=11.35 RMSE=15.51 R2=0.468
🏃 View run rf-baseline at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/45eb261a162e4cf698279938060aebb3
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

[codecarbon WARNING @ 11:37:48] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 11:37:52] >>> Tracker's metadata:
[codecarbon INFO @ 11:37:52]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 11:37:52]   Python version: 3.11.9
[codecarbon INFO @ 11:37:52]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 11:37:52]   Available RAM : 9.940 GB
[codecarbon INFO @ 11:37:52]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 11:37:52]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 11:37:52]   GPU count: 0
[codecarbon INFO @ 11:37:52]   GPU model:
[codecarbon INFO @ 11:37:52] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:37:52] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 7.994690626914437 W
[codecarbon INFO @ 11:37:52] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 11:37:52] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:38:08] Energy consumed for RAM : 0.000042 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:38:08] Delta energy consumed for CPU with windows_emi : 0.000040 kWh, power : 9.610548334703132 W
[codecarbon INFO @ 11:38:08] Energy consumed for All CPU : 0.000040 kWh
[codecarbon INFO @ 11:38:08] 0.000082 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:38:23] Energy consumed for RAM : 0.000084 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:38:23] Delta energy consumed for CPU with windows_emi : 0.000041 kWh, power : 9.718435086593217 W
[codecarbon INFO @ 11:38:23] Energy consumed for All CPU : 0.000081 kWh
[codecarbon INFO @ 11:38:23] 0.000165 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:38:38] Energy consumed for RAM : 0.000126 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:38:38] Delta energy consumed for CPU with windows_emi : 0.000041 kWh, power : 9.859258872037476 W
[codecarbon INFO @ 11:38:38] Energy consumed for All CPU : 0.000122 kWh
[codecarbon INFO @ 11:38:38] 0.000248 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:38:53] Energy consumed for RAM : 0.000167 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:38:53] Delta energy consumed for CPU with windows_emi : 0.000040 kWh, power : 9.610403069669651 W
[codecarbon INFO @ 11:38:53] Energy consumed for All CPU : 0.000162 kWh
[codecarbon INFO @ 11:38:53] 0.000330 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:39:08] Energy consumed for RAM : 0.000209 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:39:08] Delta energy consumed for CPU with windows_emi : 0.000040 kWh, power : 9.617308930996545 W
[codecarbon INFO @ 11:39:08] Energy consumed for All CPU : 0.000202 kWh
[codecarbon INFO @ 11:39:08] 0.000411 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:39:23] Energy consumed for RAM : 0.000250 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:39:23] Delta energy consumed for CPU with windows_emi : 0.000040 kWh, power : 9.593116522765586 W
[codecarbon INFO @ 11:39:23] Energy consumed for All CPU : 0.000242 kWh
[codecarbon INFO @ 11:39:23] 0.000493 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:39:32] Energy consumed for RAM : 0.000275 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:39:32] Delta energy consumed for CPU with windows_emi : 0.000022 kWh, power : 9.034506453291465 W
[codecarbon INFO @ 11:39:32] Energy consumed for All CPU : 0.000265 kWh
[codecarbon INFO @ 11:39:32] 0.000539 kWh of electricity and 0.000000 L of water were used since the beginning.

rf-n200: MAE=11.28 RMSE=15.43 R2=0.473
🏃 View run rf-n200 at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/ba9a2078bc194ea59a63ee662f0963b9
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2

[codecarbon WARNING @ 11:39:38] Multiple instances of codecarbon are allowed to run at the same time.
[codecarbon INFO @ 11:40:02] >>> Tracker's metadata:
[codecarbon INFO @ 11:40:02]   Platform system: Windows-10-10.0.26200-SP0
[codecarbon INFO @ 11:40:02]   Python version: 3.11.9
[codecarbon INFO @ 11:40:02]   CodeCarbon version: 3.3.1
[codecarbon INFO @ 11:40:02]   Available RAM : 9.940 GB
[codecarbon INFO @ 11:40:02]   CPU count: 8 thread(s) in 1 physical CPU(s)
[codecarbon INFO @ 11:40:02]   CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
[codecarbon INFO @ 11:40:02]   GPU count: 0
[codecarbon INFO @ 11:40:02]   GPU model:
[codecarbon INFO @ 11:40:02] Energy consumed for RAM : 0.000000 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:40:02] Delta energy consumed for CPU with windows_emi : 0.000000 kWh, power : 6.692548582024073 W
[codecarbon INFO @ 11:40:02] Energy consumed for All CPU : 0.000000 kWh
[codecarbon INFO @ 11:40:02] 0.000000 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:40:17] Energy consumed for RAM : 0.000042 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:40:17] Delta energy consumed for CPU with windows_emi : 0.000039 kWh, power : 9.411340432057608 W
[codecarbon INFO @ 11:40:17] Energy consumed for All CPU : 0.000039 kWh
[codecarbon INFO @ 11:40:17] 0.000081 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:40:32] Energy consumed for RAM : 0.000083 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:40:32] Delta energy consumed for CPU with windows_emi : 0.000040 kWh, power : 9.53337102354708 W
[codecarbon INFO @ 11:40:32] Energy consumed for All CPU : 0.000079 kWh
[codecarbon INFO @ 11:40:32] 0.000162 kWh of electricity and 0.000000 L of water were used since the beginning.
[codecarbon INFO @ 11:40:45] Energy consumed for RAM : 0.000121 kWh. RAM Power : 10.0 W
[codecarbon INFO @ 11:40:45] Delta energy consumed for CPU with windows_emi : 0.000035 kWh, power : 9.307761735368251 W
[codecarbon INFO @ 11:40:45] Energy consumed for All CPU : 0.000114 kWh
[codecarbon INFO @ 11:40:46] 0.000235 kWh of electricity and 0.000000 L of water were used since the beginning.

rf-maxfeat05: MAE=11.23 RMSE=15.35 R2=0.478
🏃 View run rf-maxfeat05 at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2/runs/5923cd54963e4a0baaff04fd7dd30193
🧪 View experiment at: https://dagshub.com/sergi.gonzalez.martos/MLOps_AlgoRhythm.mlflow/#/experiments/2